version: '3.3'

volumes:
    postgres_data: {}

services:
  frontend:
    image: node:10-alpine
    command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend:/app
    working_dir: /app
    restart: on-failure
    ports: 
      - "8000:8080"
